version: '3'

services:
  postgresql:
    image: postgres
    container_name: git
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=git
      - POSTGRES_PASSWORD=git
      - POSTGRES_DATABASE=git
    command: postgres
    restart: always
